table Histórico
	lineageTag: 86afa604-15cb-44d1-925d-ef62c2065db6

	column fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7cb9cd52-6090-4158-863e-fc4195f69d46
		summarizeBy: none
		sourceColumn: fecha

		variation Variación
			isDefault
			relationship: bb70c597-bcd4-4eb3-88b7-2866a435945b
			defaultHierarchy: LocalDateTable_ac988185-f5f2-4eb3-9e92-27d0dfb23503.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column tipo_cambio
		dataType: double
		lineageTag: ac6a3428-d6a7-4137-8f7c-6524693567fb
		summarizeBy: sum
		sourceColumn: tipo_cambio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column variacion_diaria_pct
		dataType: double
		lineageTag: 670a952e-66ad-47b9-a6ba-eff6812ea18a
		summarizeBy: sum
		sourceColumn: variacion_diaria_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column variacion_mensual_pct
		dataType: double
		lineageTag: 6bbe7b74-f3aa-4d59-bc75-d51c8f6c4ccc
		summarizeBy: sum
		sourceColumn: variacion_mensual_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ma_30d
		dataType: double
		lineageTag: 9a1be6d5-7b13-407d-8558-b3925f5d7dbe
		summarizeBy: sum
		sourceColumn: ma_30d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ma_90d
		dataType: double
		lineageTag: 5989feee-b50f-4045-9f20-8bfb55c926f9
		summarizeBy: sum
		sourceColumn: ma_90d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column volatilidad_30d
		dataType: double
		lineageTag: baa0009d-b89c-4de4-b0f5-8e9f018dd1b9
		summarizeBy: sum
		sourceColumn: volatilidad_30d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column año
		dataType: int64
		lineageTag: 2f89dd4b-6f0b-4f39-9df4-bcb6e65f5b3b
		summarizeBy: none
		sourceColumn: año

	column fecha_grafico
		dataType: string
		lineageTag: d5f2c6a1-4c8e-4d3a-b7f9-1e6a2c8d4b70
		summarizeBy: none
		sourceColumn: fecha_grafico

	column mes_grafico
		dataType: string
		lineageTag: e1b7c4d9-5f28-4a63-8c0e-2d9f6b1a7e35
		summarizeBy: none
		sourceColumn: mes_grafico

	partition Histórico = m
		mode: import
		source =
				let
				  Origen = Excel.Workbook(File.Contents("D:\PORTAFOLIO\Automatizacion\output\reporte_financiero.xlsx"), null, true),
				  #"Navegación 1" = Origen{[Item = "Histórico", Kind = "Sheet"]}[Data],
				  #"Encabezados promovidos" = Table.PromoteHeaders(#"Navegación 1", [PromoteAllScalars = true]),
				  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"fecha", type date}, {"tipo_cambio", type number}, {"variacion_diaria_pct", type number}, {"variacion_mensual_pct", type number}, {"ma_30d", type number}, {"ma_90d", type number}, {"volatilidad_30d", type number}}, "es"),
				  #"Fecha gráfico agregada" = Table.AddColumn(#"Tipo de columna cambiado", "fecha_grafico", each Date.ToText([fecha], "yyyy-MM-dd"), type text),
				  #"Mes gráfico agregado" = Table.AddColumn(#"Fecha gráfico agregada", "mes_grafico", each Date.ToText([fecha], "yyyy-MM"), type text),
				  #"Año agregado" = Table.AddColumn(#"Mes gráfico agregado", "año", each Date.Year([fecha]), Int64.Type)
				in
				  #"Año agregado"

	annotation PBI_ResultType = Table

